export const formIoData = {
  "components": [
      {
          "label": "Text Area",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
              "type": "input"
          },
          "displayMask": "",
          "applyMaskOn": "change",
          "editor": "",
          "autoExpand": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "persistent": true,
          "inputFormat": "html",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "truncateMultipleSpaces": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
              "required": false,
              "pattern": "",
              "customMessage": "",
              "custom": "",
              "customPrivate": false,
              "json": "",
              "minLength": "",
              "maxLength": "",
              "minWords": "",
              "maxWords": "",
              "strictDateValidation": false,
              "multiple": false,
              "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "errors": "",
          "key": "textArea",
          "tags": [],
          "properties": {},
          "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
          },
          "type": "textarea",
          "rows": 3,
          "wysiwyg": false,
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "allowMultipleMasks": false,
          "addons": [],
          "mask": false,
          "inputType": "text",
          "inputMask": "",
          "fixedSize": true,
          "id": "ech68g8",
          "defaultValue": null
      },
      {
          "label": "Submit",
          "action": "submit",
          "showValidations": false,
          "theme": "primary",
          "size": "md",
          "block": false,
          "leftIcon": "",
          "rightIcon": "",
          "shortcut": "",
          "description": "",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "disableOnInvalid": false,
          "hidden": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "key": "submit",
          "tags": [],
          "properties": {},
          "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
          },
          "type": "button",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "dataGridLabel": true,
          "labelPosition": "top",
          "errorLabel": "",
          "hideLabel": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {
              "type": "input"
          },
          "validateOn": "change",
          "validate": {
              "required": false,
              "custom": "",
              "customPrivate": false,
              "strictDateValidation": false,
              "multiple": false,
              "unique": false
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "ed1mcn"
      },
      {
          "label": "Number",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
              "type": "input"
          },
          "displayMask": "",
          "applyMaskOn": "change",
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "mask": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "multiple": false,
          "persistent": true,
          "delimiter": false,
          "requireDecimal": false,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "truncateMultipleSpaces": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
              "required": false,
              "customMessage": "",
              "custom": "",
              "customPrivate": false,
              "json": "",
              "min": "",
              "max": "",
              "strictDateValidation": false,
              "multiple": false,
              "unique": false,
              "step": "any",
              "integer": ""
          },
          "errorLabel": "",
          "errors": "",
          "key": "number",
          "tags": [],
          "properties": {},
          "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
          },
          "type": "number",
          "input": true,
          "unique": false,
          "refreshOn": "",
          "dataGridLabel": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "eagvp2s",
          "defaultValue": null
      },
      {
          "label": "Password",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
              "type": "input"
          },
          "displayMask": "",
          "applyMaskOn": "change",
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "case": "",
          "truncateMultipleSpaces": false,
          "redrawOn": "",
          "clearOnHide": true,
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
              "required": false,
              "pattern": "",
              "customMessage": "",
              "custom": "",
              "customPrivate": false,
              "json": "",
              "minLength": "",
              "maxLength": "",
              "strictDateValidation": false,
              "multiple": false,
              "unique": false
          },
          "errorLabel": "",
          "errors": "",
          "key": "password",
          "tags": [],
          "properties": {},
          "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
          },
          "type": "password",
          "input": true,
          "multiple": false,
          "defaultValue": null,
          "protected": true,
          "unique": false,
          "persistent": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "encrypted": false,
          "allowMultipleMasks": false,
          "addons": [],
          "mask": false,
          "inputType": "text",
          "inputFormat": "plain",
          "inputMask": "",
          "id": "eo1qm5"
      },
      {
          "label": "Text Field",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
              "type": "input"
          },
          "inputMask": "",
          "displayMask": "",
          "applyMaskOn": "change",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "truncateMultipleSpaces": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
              "required": false,
              "pattern": "",
              "customMessage": "",
              "custom": "",
              "customPrivate": false,
              "json": "",
              "minLength": "",
              "maxLength": "",
              "strictDateValidation": false,
              "multiple": false,
              "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "errors": "",
          "key": "textField",
          "tags": [],
          "properties": {},
          "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "addons": [],
          "inputType": "text",
          "id": "er19zpi",
          "defaultValue": null
      }
  ]
}

// export const formIoData = {
//     display: "form",
//     components: [
//       {
//         label: "Checkbox",
//         tableView: false,
//         key: "checkbox",
//         type: "checkbox",
//         input: true
//       },
  
//       {
//         label: "Text Field",
//         tableView: true,
//         validate: {
//           // pattern: "/^([A-Z][a-z .'-]*)*$/",
//           customMessage: "Test error",
//           // "custom": "valid = (input !== 'Joe')",
//           minLength: 3,
//           maxLength: 10
//         },
//         errorLabel: "Please fill in only letters.",
//         key: "textField",
//         type: "textfield",
//         input: true
//       },
//       {
//         type: "button",
//         label: "Submit",
//         key: "submit",
//         disableOnInvalid: true,
//         input: true,
//         tableView: false
//       }
//     ]
//   };
  